# Relatório de Análise V

## Tratamento de Dados Faltantes

In [1]:
import pandas as pd

In [2]:
dados = pd.read_csv('dados/aluguel_residencial.csv', sep = ';')

In [3]:
dados.head(10)

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU,Valor m2,Tipo Agregado
0,Quitinete,Copacabana,1,0,0,40,1700.0,500.0,60.0,42.50,Apartamento
1,Casa,Jardim Botânico,2,0,1,100,7000.0,0.0,0.0,70.00,Casa
2,Apartamento,Centro,1,0,0,15,800.0,390.0,20.0,53.33,Apartamento
3,Apartamento,Higienópolis,1,0,0,48,800.0,230.0,0.0,16.67,Apartamento
4,Apartamento,Cachambi,2,0,0,50,1300.0,301.0,17.0,26.00,Apartamento
5,Casa de Condomínio,Barra da Tijuca,5,4,5,750,22000.0,0.0,0.0,29.33,Casa
6,Casa de Condomínio,Ramos,2,2,0,65,1000.0,0.0,0.0,15.38,Casa
7,Apartamento,Grajaú,2,1,0,70,1500.0,642.0,74.0,21.43,Apartamento
8,Apartamento,Lins de Vasconcelos,3,1,1,90,1500.0,455.0,14.0,16.67,Apartamento
9,Apartamento,Copacabana,1,0,1,40,2000.0,561.0,50.0,50.00,Apartamento

In [4]:
dados.isnull()

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU,Valor m2,Tipo Agregado
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
21796,False,False,False,False,False,False,False,False,False,False,False
21797,False,False,False,False,False,False,False,False,False,False,False
21798,False,False,False,False,False,False,False,False,False,False,False
21799,False,False,False,False,False,False,False,False,False,False,False
21800,False,False,False,False,False,False,False,False,False,False,False
21801,False,False,False,False,False,False,False,False,False,False,False
21802,False,False,False,False,False,False,False,False,False,False,False
21803,False,False,False,False,False,False,False,False,False,False,False
21804,False,False,False,False,False,False,False,False,False,False,False
21805,False,False,False,False,False,False,False,False,False,False,False
21806,False,False,False,False,False,False,False,False,False,False,False
21807,False,False,False,False,False,False,False,False,False,False,False
21808,False,False,False,False,False,False,False,False,False,False,False
21809,False,False,False,False,False,False,False,False,False,False,False
21810,False,False,False,False,False,False,False,False,False,False,False
21811,False,False,False,False,False,False,False,False,False,False,False
21812,False,False,False,False,False,False,False,False,False,False,False
21813,False,False,False,False,False,False,False,False,False,False,False
21814,False,False,False,False,False,False,False,False,False,False,False
21815,False,False,False,False,False,False,False,False,False,False,False
21816,False,False,False,False,False,False,False,False,False,False,False
21817,False,False,False,False,False,False,False,False,False,False,False
21818,False,False,False,False,False,False,False,False,False,False,False
21819,False,False,False,False,False,False,False,False,False,False,False
21820,False,False,False,False,False,False,False,False,False,False,False
21821,False,False,False,False,False,False,False,False,False,False,False
21822,False,False,False,False,False,False,False,False,False,False,False
21823,False,False,False,False,False,False,False,False,False,False,False
21824,False,False,False,False,False,False,False,False,False,False,False
21825,False,False,False,False,False,False,False,False,False,False,False

In [5]:
dados.notnull()

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU,Valor m2,Tipo Agregado
0,True,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,True
5,True,True,True,True,True,True,True,True,True,True,True
6,True,True,True,True,True,True,True,True,True,True,True
7,True,True,True,True,True,True,True,True,True,True,True
8,True,True,True,True,True,True,True,True,True,True,True
9,True,True,True,True,True,True,True,True,True,True,True
10,True,True,True,True,True,True,True,True,True,True,True
11,True,True,True,True,True,True,True,True,True,True,True
12,True,True,True,True,True,True,True,True,True,True,True
13,True,True,True,True,True,True,True,True,True,True,True
14,True,True,True,True,True,True,True,True,True,True,True
15,True,True,True,True,True,True,True,True,True,True,True
16,True,True,True,True,True,True,True,True,True,True,True
17,True,True,True,True,True,True,True,True,True,True,True
18,True,True,True,True,True,True,True,True,True,True,True
19,True,True,True,True,True,True,True,True,True,True,True
20,True,True,True,True,True,True,True,True,True,True,True
21,True,True,True,True,True,True,True,True,True,True,True
22,True,True,True,True,True,True,True,True,True,True,True
23,True,True,True,True,True,True,True,True,True,True,True
24,True,True,True,True,True,True,True,True,True,True,True
25,True,True,True,True,True,True,True,True,True,True,True
26,True,True,True,True,True,True,True,True,True,True,True
27,True,True,True,True,True,True,True,True,True,True,True
28,True,True,True,True,True,True,True,True,True,True,True
29,True,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...
21796,True,True,True,True,True,True,True,True,True,True,True
21797,True,True,True,True,True,True,True,True,True,True,True
21798,True,True,True,True,True,True,True,True,True,True,True
21799,True,True,True,True,True,True,True,True,True,True,True
21800,True,True,True,True,True,True,True,True,True,True,True
21801,True,True,True,True,True,True,True,True,True,True,True
21802,True,True,True,True,True,True,True,True,True,True,True
21803,True,True,True,True,True,True,True,True,True,True,True
21804,True,True,True,True,True,True,True,True,True,True,True
21805,True,True,True,True,True,True,True,True,True,True,True
21806,True,True,True,True,True,True,True,True,True,True,True
21807,True,True,True,True,True,True,True,True,True,True,True
21808,True,True,True,True,True,True,True,True,True,True,True
21809,True,True,True,True,True,True,True,True,True,True,True
21810,True,True,True,True,True,True,True,True,True,True,True
21811,True,True,True,True,True,True,True,True,True,True,True
21812,True,True,True,True,True,True,True,True,True,True,True
21813,True,True,True,True,True,True,True,True,True,True,True
21814,True,True,True,True,True,True,True,True,True,True,True
21815,True,True,True,True,True,True,True,True,True,True,True
21816,True,True,True,True,True,True,True,True,True,True,True
21817,True,True,True,True,True,True,True,True,True,True,True
21818,True,True,True,True,True,True,True,True,True,True,True
21819,True,True,True,True,True,True,True,True,True,True,True
21820,True,True,True,True,True,True,True,True,True,True,True
21821,True,True,True,True,True,True,True,True,True,True,True
21822,True,True,True,True,True,True,True,True,True,True,True
21823,True,True,True,True,True,True,True,True,True,True,True
21824,True,True,True,True,True,True,True,True,True,True,True
21825,True,True,True,True,True,True,True,True,True,True,True

In [6]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21826 entries, 0 to 21825
Data columns (total 11 columns):
Tipo             21826 non-null object
Bairro           21826 non-null object
Quartos          21826 non-null int64
Vagas            21826 non-null int64
Suites           21826 non-null int64
Area             21826 non-null int64
Valor            21826 non-null float64
Condominio       21826 non-null float64
IPTU             21826 non-null float64
Valor m2         21826 non-null float64
Tipo Agregado    21826 non-null object
dtypes: float64(4), int64(4), object(3)
memory usage: 1.8+ MB

In [7]:
dados[dados['Valor'].isnull()]

Empty DataFrame
Columns: [Tipo, Bairro, Quartos, Vagas, Suites, Area, Valor, Condominio, IPTU, Valor m2, Tipo Agregado]
Index: []

In [21]:
A = dados.shape[0]
A

21826

In [22]:
A = dados.shape[0]
dados.dropna(subset = ['Valor'], inplace = True)
B = dados.shape[0]
A - B

0

In [10]:
dados[dados['Valor'].isnull()]

Empty DataFrame
Columns: [Tipo, Bairro, Quartos, Vagas, Suites, Area, Valor, Condominio, IPTU, Valor m2, Tipo Agregado]
Index: []

## Tratamento de Dados Faltantes (continuação)

In [11]:
dados[dados['Condominio'].isnull()].shape[0]

0

In [23]:
selecao = (dados['Tipo'] == 'Apartamento') & (dados['Condominio'].isnull())

In [24]:
A = dados.shape[0]
dados = dados[~selecao]
B = dados.shape[0]
A - B

0

In [25]:
dados[dados['Condominio'].isnull()].shape[0]

0

In [26]:
dados = dados.fillna({'Condominio': 0, 'IPTU': 0})

In [27]:
dados[dados['Condominio'].isnull()].shape[0]

0

In [28]:
dados[dados['IPTU'].isnull()].shape[0]

0

In [18]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 21826 entries, 0 to 21825
Data columns (total 11 columns):
Tipo             21826 non-null object
Bairro           21826 non-null object
Quartos          21826 non-null int64
Vagas            21826 non-null int64
Suites           21826 non-null int64
Area             21826 non-null int64
Valor            21826 non-null float64
Condominio       21826 non-null float64
IPTU             21826 non-null float64
Valor m2         21826 non-null float64
Tipo Agregado    21826 non-null object
dtypes: float64(4), int64(4), object(3)
memory usage: 2.0+ MB

In [19]:
dados.to_csv('dados/aluguel_residencial.csv', sep = ';', index = False)